### DISCUSSION TITLE
Custom token: as input or environ?

### DISCUSSION THREAD

**Discussion by tobon4** [lycheeverse/lychee#1353] [Q&A] [answered]
In our repositories we sometimes link to other repositories. I don't get this to work using token as input (access denied (404)): 
```
- uses: lycheeverse/lychee-action@v1.9.0
  with: 
    token: ${{ secrets.CUSTOM_TOKEN }}
```
However, it works if passed as environment: 
```
- uses: lycheeverse/lychee-action@v1.9.0
  with: 
     args: <args>
     ...
   env:
      GITHUB_TOKEN: ${{ secrets.CUSTOM_TOKEN  }}
```
I don't see this in the documentation - am I missing it or is it not documented?

**Comment by mre** [comment, marked as answer]
It should work like you described.
We have the following code in the action:

https://github.com/lycheeverse/lychee-action/blob/8c9a282bef269f1ba1f727d1f79c5b8139bf3a5a/entrypoint.sh#L13-L16

This merges the input token.

However, when I introduced a custom input token, I think I forgot to pass the correct argument/input to the action.
See https://github.com/lycheeverse/lychee-action/pull/222/files for the fix.

If you have some time, could you try if it works with that version?
You should be able to do

```yaml
- uses: lycheeverse/lychee-action@0ff48c676a36e0f3fa8b30ae9188f3c14409c520
  with: 
    token: ${{ secrets.CUSTOM_TOKEN }}
```

After a successful test, we can merge this.

Thanks for raising this.
