### DISCUSSION TITLE
Is there a way to check an insecure link?

### DISCUSSION THREAD

**Discussion by Pbarbosa92** [lycheeverse/lychee#1387] [Q&A]
Hi, I'm using your link checker action and I got this error
"Failed: Network error: error:0A000086:SSL routines:tls_post_process_server_certificate:certificate verify failed:ssl/statem/statem_clnt.c:1890: (unable to get local issuer certificate)"

If I add the -I --insecure flag it will just skip the url. 
Is there a way to still check the url?

**Comment by mre** [comment]
Hey,

can you post the link here?
You can rewrite it to http if you want to check that the http link works (but https doesn't work).


```sh
> echo 'https://corrode.dev' | lychee -v --remap 'https http' -
✔ [200] http://corrode.dev/

🔍 1 Total (in 0s) ✅ 1 OK 🚫 0 Errors
```

**Reply by Pbarbosa92** [reply]
The link is already http
http://ccrm.vims.edu/schismweb/

**Reply by mre** [reply]
That's weird because then it should not fail on SSL. Unless there is a way where http gets served via TLS (essentially https)

**Reply by mre** [reply]
It works for me, though: 

```sh
> echo 'http://ccrm.vims.edu/schismweb/' | lychee -
  1/1 ━━━━━━━━━━━━━━━━━━━━ Finished extracting links                                                                                                                                                               🔍 1 Total (in 1s) ✅ 1 OK 🚫 0 Errors
```

You say you use the GitHub action?
Can you post the workflow here?
Maybe you need to install the `ca-certificates` package
https://users.rust-lang.org/t/https-unable-to-get-local-issuer-certificate/76376/4

Before you run lychee:

```yaml
      - name: Install system dependencies
        run: |
          apt-get update && apt-get install -y --no-install-recommends ca-certificates
```

I'm not sure if that's the reason. Haven't seen that case before.

**Reply by Pbarbosa92** [reply]
I've added `sudo apt-get install -y ca-certificates`
 and I get the same error. 
```
- name: Link Checker
      uses: lycheeverse/lychee-action@v1.9.0
      with:
        fail: true
        args: --base . --no-progress './**/*.md'
```
This is the part relative to the link checker. If I can't figure it out, I probably will add the link to a list of ignores because this is the only URL that behaves like this.
