### ISSUE TITLE
Skip/Exclude Unallowed URL Schemes

### ISSUE THREAD

**Issue by praneesha** [lycheeverse/lychee#106]
@mre - I get the below output when I run the link checker. All the 6 links marked as errors are correct and working. Therefore, how can I skip/exclude them from being checked?

<img width="1098" alt="Screenshot 2021-01-12 at 08 45 09" src="https://user-images.githubusercontent.com/11707273/104265091-d89cd200-54b2-11eb-90ef-a2df9d21ef2b.png">

My config is as follows:

```
on: [pull_request]
name: Link Checker 
jobs:
  linkChecker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build the site
        uses: shafreenAnfar/jekyll-build-action@v5
      - name: Lychee link checker action
        id: lc
        uses: lycheeverse/lychee-action@v1
        with:
          args: --exclude-link-local
      - name: Archive production artifacts
        uses: actions/upload-artifact@v2
        with:
          name: Link Checker Report
          path:  ./lychee/out.md  
      - name: Fail if there were link errors
        run: exit ${{ steps.lc.outputs.exit_code }}
```

**Comment by mre** [comment]
Hey,
lychee supports exclude patterns, which are just regular expressions, so something like this should work:

```
lychee links.txt --exclude twitter.com --exclude novacodecamp.com --verbose
```

**Comment by mre** [comment]
The `mailto` links work for me with the latest lychee (0.5). So with the above command I get:

```
👻 https://novacodecamp.com/app/speakers/asdfljjf
👻 https://twitter.com/matthiasendler
👻 https://twitter.com/ballerinalang
✅ contact@ballerina.io [200 OK]

📝 Summary
-------------------
🔍 Total: 4
✅ Successful: 1
⏳ Timeouts: 0
🔀 Redirected: 0
👻 Excluded: 3
🚫 Errors: 0
```

**Comment by praneesha** [comment]
@mre - Giving the args like this doesn't work.

```
      - name: Lychee link checker action
        id: lc
        uses: lycheeverse/lychee-action@v1
        with:
          args: --exclude twitter.com --exclude novacodecamp.com 
 ```
  
<img width="1100" alt="Screenshot 2021-01-12 at 15 58 26" src="https://user-images.githubusercontent.com/11707273/104302620-07d13480-54ef-11eb-9370-707e3abf00dc.png">

How can I get this resolved?
