### ISSUE TITLE
`--exclude` argument not excluding files that match pattern

### ISSUE THREAD

**Issue by pjlewisuk** [lycheeverse/lychee#1280]
We have a GitHub action that uses the lychee-action to check for broken links:

```yaml
      - name: Html Broken Link Checker
        id: lychee
        uses: lycheeverse/lychee-action@v1.7.0
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
        with:
          args: "helper/localsite.html --exclude './*.svg' './*.png' -n"
          # Fail action on broken links
          fail: true
```

Recently, this job has started failing because of a missing PNG:

```
lychee
Run /home/runner/work/_actions/lycheeverse/lychee-action/v1.7.0/entrypoint.sh
  /home/runner/work/_actions/lycheeverse/lychee-action/v1.7.0/entrypoint.sh
  shell: /usr/bin/bash --noprofile --norc -e -o pipefail ***0***
  env:
    AZCLIVERSION: 2.[53](https://github.com/org/repo-name/actions/runs/6643578305/job/18056283197?pr=668#step:12:56).0
    GITHUB_TOKEN: ***
    INPUT_GITHUB_TOKEN: 
    INPUT_ARGS: helper/localsite.html --exclude './*.svg' './*.png' -n
    INPUT_DEBUG: false
    INPUT_FAIL: true
    INPUT_FORMAT: markdown
    INPUT_JOBSUMMARY: true
    INPUT_OUTPUT: lychee/out.md
✗ [ERR] file:///home/runner/work/repo-name/repo-name/helper/image.png | Failed: Cannot find file
## Summary

| Status        | Count |
|---------------|-------|
| 🔍 Total      | 22    |
| ✅ Successful | 19    |
| ⏳ Timeouts   | 0     |
| 🔀 Redirected | 0     |
| 👻 Excluded   | 2     |
| ❓ Unknown    | 0     |
| 🚫 Errors     | 1     |

## Errors per input

### Errors in helper/localsite.html

* [ERR] file:///home/runner/work/repo-name/repo-name/helper/image.png | Failed: Cannot find file
```

I know I could simply add the image in, but I'm trying to figure out why the `--exclude` parameter is being ignore. We recently jumped from `lychee-action@v1.5.4` to `lychee-action@v1.8.0`, which is when the errors started.

If I add the same exclusions (*.svg, *.png) to the `.lycheeignore` file it is ignore correctly, so is this now the correct way to exclude files and paths?
