### ISSUE TITLE
Wrong error on emails in Gitlab-CI

### ISSUE THREAD

**Issue by fauust** [lycheeverse/lychee#136]
Hi,
lychee in GitLab-CI wrongly reports error on email addresses, see:
https://salsa.debian.org/faust/go-team.pages.debian.net/-/jobs/1427125#L150-L151

![screenshot_20210209_154154](https://user-images.githubusercontent.com/2197555/107379625-6806c680-6aed-11eb-84e9-455feeadb237.png)

Here is the yaml part:
```yaml
check:
  stage: check
  script:
    - apt-get update -qq && apt-get install -y -qq wget
    - wget -qO- "https://github.com/lycheeverse/lychee/releases/download/v0.5.0/lychee-v0.5.0-x86_64-unknown-linux-gnu.tar.gz" | tar -xz
    - ./lychee --verbose --exclude="irc://irc.debian.org:6667" --exclude="https://anonscm.debian.org" build/*.html
```

When running it locally, no error is detected:
```console
❯ ./lychee --verbose --exclude="irc://irc.debian.org:6667" --exclude="https://anonscm.debian.org" build/*.html | grep @
✅ git@salsa.debian.org [200 OK]
✅ team+pkg-go@tracker.debian.org [200 OK]
```

Am I missing something?
