### ISSUE TITLE
Don't tag nightly pre-releases

### ISSUE THREAD

**Issue by varac** [lycheeverse/lychee#1601]
I'm using the lychee pre-commit hook. 
pre-commit has a nifty `autoupdate` subcommand which updates all configured hooks to their latest git tags (which is considered by pre-commit as the latest stable release). 
In the case of lychee, it will always update to the `nightly` git tag, which is not what I want. Could be maybe not use a nightly tag please ? If it always points to the main branch HEAD it's kind of useless anyway. It it's only needed for the GitHub nightly release maybe there's another way of shipping an automated nightly release without a dedicated (moving) git tag.
Thanks !

**Comment by mre** [comment]
Hey @varac, thanks for bringing this up! While looking at this, I also noticed that our [pre-commit-hooks.yml](https://github.com/lycheeverse/lychee/blob/master/.pre-commit-hooks.yaml) example has an outdated Docker image version (0.14 while we're at 0.18 now).

For pre-commit users, I believe the recommended approach would be to pin to specific versions in their config, like this:

```yaml
- id: lychee
  name: lychee
  description: "Run 'lychee' for fast, async, stream-based link checking"
  entry: lychee
  language: system
  args: ["--no-progress"]
  types: [text]
  pass_filenames: true
  require_serial: true
  rev: "v0.18.0"  # Pin to a specific version
```

Or for Docker users:
```yaml
- id: lychee-docker
  name: lychee
  description: "Run 'lychee' docker image for fast, async, stream-based link checking"
  entry: lycheeverse/lychee:0.18  # Updated to latest version
  language: docker_image
  args: ["--no-progress"]
  types: [text]
  pass_filenames: true
  require_serial: true
```

That said, I'm not an expert on pre-commit's best practices and might be overlooking important considerations. I'd appreciate any corrections or suggestions on how to better handle this!

For now, we use the `nightly` tag for our automated builds and Docker images. Would pinning versions in the pre-commit config work for your use case? Let me know what you think!
