### ISSUE TITLE
problems with lychee pre-commit installation

### ISSUE THREAD

**Issue by dpinol** [lycheeverse/lychee#1635]
1) With the following pre-commit configuration as per the README.md, running "pre-commit run --all lychee" fails with error "Executable `lychee` not found". I had to `cd` into the pre-commit environment and manually run "make install".
```
  - repo: https://github.com/lycheeverse/lychee.git
    rev: v0.15.1
    hooks:
      - id: lychee
        # Optionally include additional CLI arguments
        args: ["--no-progress", "--exclude", "file://"]
```

2) Above v0.15.1, the rev pre-commit field must have the syntax "lychee-v0.1X.X". Is this intended? All pre-commit hooks I've  seen have revisions with  format "v9.9.9"

thanks

**Comment by mre** [comment]
It looks like there are two distinct issues being reported:

1. Pre-commit hook installation failure
The error "Executable `lychee` not found" suggests the pre-commit hook isn't properly installing the lychee binary. Having to manually `cd` into the pre-commit environment and run "make install" shouldn't be necessary. This likely indicates an issue with the hook's installation script.

Have you tried any of these steps?
- Clearing your pre-commit cache: `pre-commit clean`
- Updating pre-commit: `pre-commit autoupdate`

2. Version tag format change
The prefix was automatically added when we switched to release-plz. I'm not too happy with that change, as it caused many problems. At the moment, I wouldn't want to switch back to non-prefixed releases as I know it will break a lot of things again. Sorry about that.

Does that mean you changed the above version string from `rev: v0.15.1` to  `rev: lychee-v0.15.1`?
If not, you can try adapting your pre-commit config like this to see if it works out of the box:

```yaml
- repo: https://github.com/lycheeverse/lychee.git
  rev: lychee-v0.18.1  # If using newer versions
  hooks:
    - id: lychee
      args: ["--no-progress", "--exclude", "file://"]
```

(You probably have to re-install the hook.)

Would you be able to provide:
1. Your operating system details
2. The output of `pre-commit --version`

This would help us identify if this is a broader issue that needs to be addressed in the documentation or codebase.

**Comment by lyndonlim27** [comment]
> Also, I wonder if someone else got it to work? If there's anyone reading this who uses the pre-commit configuration, please add a comment.

Hi I am facing the same issue as well.

<img width="702" alt="Image" src="https://github.com/user-attachments/assets/cd5dfe66-068b-4fc3-9104-5f508d263261" />

pre-commit configuration:

```bash
repos:
  - repo: https://github.com/lycheeverse/lychee.git
    rev: lychee-v0.18.1
    hooks:
      - id: lychee
        args: ["--no-progress", "."]
        pass_filenames: false
```

Information:

Operating system: macOS Sequoia (Version 15.3)
Pre-commit version: pre-commit 4.1.0

**Comment by mre** [comment]
Thanks. Does it work if you change it to this?

```yaml
repos:
  - repo: https://github.com/lycheeverse/lychee.git
    rev: lychee-bin-v0.18.1
    hooks:
      - id: lychee
        args: ["--no-progress", "."]
        pass_filenames: false
```

**Comment by dpinol** [comment]
With lychee-bin-v0.18.1
```
pre-commit run --all lychee
[INFO] Initializing environment for https://github.com/lycheeverse/lychee.git.
An unexpected error has occurred: CalledProcessError: command: ('/usr/bin/git', 'checkout', 'lychee-bin-v0.18.1')
return code: 1
stdout: (none)
stderr:
    error: pathspec 'lychee-bin-v0.18.1' did not match any file(s) known to git
Check the log at /home/dani/.cache/pre-commit/pre-commit.log
```

With lychee-v0.18.1
```
pre-commit run --all lychee
[INFO] Initializing environment for https://github.com/lycheeverse/lychee.git.
lychee...................................................................Failed
- hook id: lychee
- exit code: 1

Executable `lychee` not found
```

**Comment by lyndonlim27** [comment]
> With lychee-bin-v0.18.1
> 
> ```
> pre-commit run --all lychee
> [INFO] Initializing environment for https://github.com/lycheeverse/lychee.git.
> An unexpected error has occurred: CalledProcessError: command: ('/usr/bin/git', 'checkout', 'lychee-bin-v0.18.1')
> return code: 1
> stdout: (none)
> stderr:
>     error: pathspec 'lychee-bin-v0.18.1' did not match any file(s) known to git
> Check the log at /home/dani/.cache/pre-commit/pre-commit.log
> ```
> 
> With lychee-v0.18.1
> 
> ```
> pre-commit run --all lychee
> [INFO] Initializing environment for https://github.com/lycheeverse/lychee.git.
> lychee...................................................................Failed
> - hook id: lychee
> - exit code: 1
> 
> Executable `lychee` not found
> ```

I face the same exact error as you too

**Comment by mre** [comment]
Clearly I don't know how pre-commit hooks, but has anyone tried this?

```yaml
- repo: https://github.com/lycheeverse/lychee.git
  rev: lychee-v0.18.1
  hooks:
    - id: lychee-bin
```
