### ISSUE TITLE
cargo binstall does not find binaries

### ISSUE THREAD

**Issue by Arteiii** [lycheeverse/lychee#1651]
```shell
cargo binstall lychee
 INFO resolve: Resolving package: 'lychee'
 WARN The package lychee v0.18.1 will be installed from source (with cargo)
```

I think the problem is with the naming of the releases and binstall not finding the compiled bins

One solution would be to add the binstall config to the `Cargo.toml` file

```toml
[package.metadata.binstall]
pkg-url = "https://github.com/mre/lychee/releases/download/lychee-v{version}/lychee-{target}{archive-suffix}"
disabled-strategies = ["compile"] 
```

https://github.com/cargo-bins/cargo-binstall/blob/main/SUPPORT.md
