### ISSUE TITLE
Intermittent github 404

### ISSUE THREAD

**Issue by jazanne** [lycheeverse/lychee#431]
These 2 links give me intermittent 404s when I run Lychee GitHub action.

I have lots of other github links that never 404, it's only these two. Any thought on why that could be?

My config

```yaml
linkChecker:
    name: "Check external links"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Link Checker
        uses: lycheeverse/lychee-action@v1.2.0
        with:
          args: --config .github/lychee.toml **/*.mdx
          fail: true
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
```

* [https://github.com/features/actions](https://github.com/features/actions): Failed: 404 Not Found: Not Found
* [https://github.com/marketplace/actions/launchdarkly-code-references](https://github.com/marketplace/actions/launchdarkly-code-references): Failed: 404 Not Found: Not Found

**Comment by mre** [comment]
Huh? That works for me. 🤔 

`foo.md`:
```
https://github.com/features/actions
https://github.com/marketplace/actions/launchdarkly-code-references
```

```
> lychee /tmp/foo.md -v                                                                                                                         ✘
✔ https://github.com/features/actions [200 OK]
✔ https://github.com/marketplace/actions/launchdarkly-code-references [200 OK]

🔍 2 Total ✅ 2 OK 🚫 0 Errors
```

**Comment by mre** [comment]
Anything special in the `lychee.toml`?

**Comment by jazanne** [comment]
not particularly - here's my config

```toml
###
### Display
###
# Verbose program output
verbose = true

# Show progress
progress = false

###
### Exclusions
###
# Exclude URLs from checking (supports regex)
exclude = [
# some private links in here
]

# Exclude all private IPs from checking
# Equivalent to setting `exclude_private`, `exclude_link_local`, and `exclude_loopback` to true
exclude_all_private = true
exclude_mail = true
```
