### ISSUE TITLE
mkdir error

### ISSUE THREAD

**Issue by jwillemsen** [lycheeverse/lychee#820]
I tried to use lychee to detect broken links in some adoc files, used the action definition below, but it fails because it can't handle asciidoctor and as a result I have a lot of errors, but also the following errors about mkdir

```
mkdir: cannot create directory ‘lychee’: File exists
/home/runner/work/_actions/lycheeverse/lychee-action/v1/entrypoint.sh: line 33: lychee/out.md: Not a directory
/home/runner/work/_actions/lycheeverse/lychee-action/v1/entrypoint.sh: line 36: lychee/out.md: Not a directory
```

```
name: Links

on:
  repository_dispatch:
  workflow_dispatch:
  schedule:
    - cron: "00 18 * * *"

jobs:
  linkChecker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Link Checker
        id: lychee
        uses: lycheeverse/lychee-action@v1
        with:
          args: --verbose --no-progress './**/*.md' './**/*.html' './**/*.adoc'
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}

      - name: Create Issue From File
        if: env.lychee_exit_code != 0
        uses: peter-evans/create-issue-from-file@v4
        with:
          title: Link Checker Report
          content-filepath: ./lychee/out.md
          labels: report, automated issue
```
