### ISSUE TITLE
add `cargo-deny` to CI

### ISSUE THREAD

**Issue by lebensterben** [lycheeverse/lychee#931]
at very least we need to comply to our license:

```toml
[licenses]
allow-osi-fsf-free = "either"
copyleft = "warn"
```
